pyuic5 -x "designer/MainWindow.ui" -o "src/ui/MainWindow.py"
pyuic5 -x "designer/tf_window.ui" -o "src/ui/tf_window.py"
pyuic5 -x "designer/case_window.ui" -o "src/ui/case_window.py"
pyuic5 -x "designer/response_window.ui" -o "src/ui/response_window.py"
pyuic5 -x "designer/fleischertow_window.ui" -o "src/ui/fleischertow_window.py"
pyuic5 -x "designer/rc_window.ui" -o "src/ui/rc_window.py"
pyuic5 -x "designer/rlc_window.ui" -o "src/ui/rlc_window.py"
echo "DONE"